apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-app
  labels:
    app: python-app
spec:
  replicas: {{ .Values.pythonApp.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: {{ .Values.pythonApp.image.repository }}:{{ .Values.pythonApp.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-mysql"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
