apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-app
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
