version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password123
    networks:
      - app-network

  python-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
